name: on_pr

on:
  pull_request:

jobs:
  ktlint:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Kotlin linter
        uses: ScaCap/action-ktlint@master
        with:
          github_token: ${{ secrets.ACTION_TOKEN }}
          reporter: github-pr-review
          android: true
