name: on_commit

on:
  push:

jobs:
  ktlint:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: ktlint
        uses: wf9a5m75/test-action@master
        with:
          # github_token: ${{ secrets.GITHUB_TOKEN }}
          # reporter: github-pr-review # Change reporter
          android: true
