name: on_commit

on:
  push:
    paths:
      - "android/app/src/**/*.kt"
      - ".github/workflows/on_commit.yml"

jobs:
  ktlint:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repository
        uses: actions/checkout@v3

      - name: Kotlin linter
        uses: vroy/gha-kotlin-linter@v1
